"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.surfacesCustomizations = exports.navigationCustomizations = exports.feedbackCustomizations = exports.dataDisplayCustomizations = exports.inputsCustomizations = void 0;
var inputs_1 = require("./inputs");
Object.defineProperty(exports, "inputsCustomizations", { enumerable: true, get: function () { return inputs_1.inputsCustomizations; } });
var dataDisplay_1 = require("./dataDisplay");
Object.defineProperty(exports, "dataDisplayCustomizations", { enumerable: true, get: function () { return dataDisplay_1.dataDisplayCustomizations; } });
var feedback_1 = require("./feedback");
Object.defineProperty(exports, "feedbackCustomizations", { enumerable: true, get: function () { return feedback_1.feedbackCustomizations; } });
var navigation_1 = require("./navigation");
Object.defineProperty(exports, "navigationCustomizations", { enumerable: true, get: function () { return navigation_1.navigationCustomizations; } });
var surfaces_1 = require("./surfaces");
Object.defineProperty(exports, "surfacesCustomizations", { enumerable: true, get: function () { return surfaces_1.surfacesCustomizations; } });
